var comuni = [
  {
    comune_codice_istat: 86016,
    mobile:
      'https://datastudio.google.com/reporting/41c08e9c-12ab-4f2b-8182-ef36cbc19d04/page/0sn7B',
    desktop:
      'https://datastudio.google.com/reporting/59d79442-4efd-4752-b640-1213850d9e43/page/0sn7B',
    comune_denominazione: 'Regalbuto',
    slug: 'regalbuto',
  },
  {
    comune_codice_istat: 86006,
    mobile: 'https://datastudio.google.com/reporting/29777cf2-7f21-49ba-b34d-f6ca250a4a49',
    desktop: 'https://datastudio.google.com/reporting/7450bed5-7638-4dbe-9026-50afa7b48fd6',
    comune_denominazione: 'Catenanuova',
    slug: 'catenanuova',
  },
  {
    comune_codice_istat: 86020,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Villarosa',
    slug: 'villarosa',
  },
  {
    comune_codice_istat: 86005,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Calascibetta',
    slug: 'calascibetta',
  },
  {
    comune_codice_istat: 82006,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Bagheria',
    slug: 'bagheria',
  },
  {
    comune_codice_istat: 82067,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Santa Flavia',
    slug: 'santa-flavia',
  },
  {
    comune_codice_istat: 82035,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Ficarazzi',
    slug: 'ficarazzi',
  },
  {
    comune_codice_istat: 82023,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Casteldaccia',
    slug: 'casteldaccia',
  },
  {
    comune_codice_istat: 82004,
    mobile: 'https://informacovid.opendatasicilia.it/',
    desktop: 'https://informacovid.opendatasicilia.it/',
    comune_denominazione: 'Altavilla Milicia',
    slug: 'altavilla-milicia',
  },
  {
    comune_codice_istat: 86004,
    mobile: 'https://datastudio.google.com/reporting/90545515-89f0-4d74-a662-88249735f722',
    desktop: 'https://datastudio.google.com/reporting/85846f70-4e77-41c2-952e-6665301f6000',
    comune_denominazione: 'Barrafranca',
    slug: 'barrafranca',
  },
  {
    comune_codice_istat: 85001,
    mobile: 'https://datastudio.google.com/s/usYtE7tOHfQ',
    desktop: 'https://datastudio.google.com/s/p-nsI4OzbUM',
    comune_denominazione: 'Acquaviva Platani',
    slug: 'acquaviva-platani',
  },
  {
    comune_codice_istat: 85002,
    mobile: 'https://datastudio.google.com/s/q8ish4DVByA',
    desktop: 'https://datastudio.google.com/s/j0uksmEsJok',
    comune_denominazione: 'Bompensiere',
    slug: 'bompensiere',
  },
  {
    comune_codice_istat: 85003,
    mobile: 'https://datastudio.google.com/s/vCw91TqgcZo',
    desktop: 'https://datastudio.google.com/s/vsCzc8j66Oc',
    comune_denominazione: 'Butera',
    slug: 'butera',
  },
  {
    comune_codice_istat: 85004,
    mobile: 'https://datastudio.google.com/s/tD4N_A9HKPg',
    desktop: 'https://datastudio.google.com/s/jUIniw2UGtA',
    comune_denominazione: 'Caltanissetta',
    slug: 'caltanissetta',
  },
  {
    comune_codice_istat: 85005,
    mobile: 'https://datastudio.google.com/s/pK2OEOSOK-k',
    desktop: 'https://datastudio.google.com/s/q42yePN7N68',
    comune_denominazione: 'Campofranco',
    slug: 'campofranco',
  },
  {
    comune_codice_istat: 85006,
    mobile: 'https://datastudio.google.com/s/goz1DZPD43w',
    desktop: 'https://datastudio.google.com/s/pmwlJW_g6kI',
    comune_denominazione: 'Delia',
    slug: 'delia',
  },
  {
    comune_codice_istat: 85007,
    mobile: 'https://datastudio.google.com/s/rvqWa1lXK1U',
    desktop: 'https://datastudio.google.com/s/s0dG_F4SQFE',
    comune_denominazione: 'Gela',
    slug: 'gela',
  },
  {
    comune_codice_istat: 85008,
    mobile: 'https://datastudio.google.com/s/q0NcQE9yq78',
    desktop: 'https://datastudio.google.com/s/kaZ5KGI5anQ',
    comune_denominazione: 'Marianopoli',
    slug: 'marianopoli',
  },
  {
    comune_codice_istat: 85009,
    mobile: 'https://datastudio.google.com/s/tuMbf7j0zx8',
    desktop: 'https://datastudio.google.com/s/s3Knzydh41E',
    comune_denominazione: 'Mazzarino',
    slug: 'mazzarino',
  },
  {
    comune_codice_istat: 85010,
    mobile: 'https://datastudio.google.com/s/mVXKnpFHC28',
    desktop: 'https://datastudio.google.com/s/krbfD-nBYUU',
    comune_denominazione: 'Milena',
    slug: 'milena',
  },
  {
    comune_codice_istat: 85011,
    mobile: 'https://datastudio.google.com/s/toYEMqfAnP4',
    desktop: 'https://datastudio.google.com/s/g3qo_8K2l0c',
    comune_denominazione: 'Montedoro',
    slug: 'montedoro',
  },
  {
    comune_codice_istat: 85012,
    mobile: 'https://datastudio.google.com/s/qkWMaKJ0YhQ',
    desktop: 'https://datastudio.google.com/s/oMVJ8PKe-Ts',
    comune_denominazione: 'Mussomeli',
    slug: 'mussomeli',
  },
  {
    comune_codice_istat: 85013,
    mobile: 'https://datastudio.google.com/s/phhSj0c3A7Q',
    desktop: 'https://datastudio.google.com/s/g1OZ4ex2ASc',
    comune_denominazione: 'Niscemi',
    slug: 'niscemi',
  },
  {
    comune_codice_istat: 85014,
    mobile: 'https://datastudio.google.com/s/ic5Lbw7vrMc',
    desktop: 'https://datastudio.google.com/s/nnAw2gWIC8Y',
    comune_denominazione: 'Resuttano',
    slug: 'resuttano',
  },
  {
    comune_codice_istat: 85015,
    mobile: 'https://datastudio.google.com/s/vyJGQP8hWFY',
    desktop: 'https://datastudio.google.com/s/q7gg9bNN4o0',
    comune_denominazione: 'Riesi',
    slug: 'riesi',
  },
  {
    comune_codice_istat: 85016,
    mobile: 'https://datastudio.google.com/s/p8QKlr2uY0Y',
    desktop: 'https://datastudio.google.com/s/ufvJcEdqcSc',
    comune_denominazione: 'San Cataldo',
    slug: 'san-cataldo',
  },
  {
    comune_codice_istat: 85017,
    mobile: 'https://datastudio.google.com/s/iZ4iF58riT0',
    desktop: 'https://datastudio.google.com/s/qizaJYxjQW4',
    comune_denominazione: 'Santa Caterina Villarmosa',
    slug: 'santa-caterina-villarmosa',
  },
  {
    comune_codice_istat: 85018,
    mobile: 'https://datastudio.google.com/s/nNXMWLC1y6s',
    desktop: 'https://datastudio.google.com/s/vWdzAd7abvw',
    comune_denominazione: 'Serradifalco',
    slug: 'serradifalco',
  },
  {
    comune_codice_istat: 85019,
    mobile: 'https://datastudio.google.com/s/pSNky9XUlEs',
    desktop: 'https://datastudio.google.com/s/mszsTEW-dpc',
    comune_denominazione: 'Sommatino',
    slug: 'sommatino',
  },
  {
    comune_codice_istat: 85020,
    mobile: 'https://datastudio.google.com/s/vnglBFJpv5w',
    desktop: 'https://datastudio.google.com/s/tMRo5U_z5-s',
    comune_denominazione: 'Sutera',
    slug: 'sutera',
  },
  {
    comune_codice_istat: 85021,
    mobile: 'https://datastudio.google.com/s/izD9zDgGbAs',
    desktop: 'https://datastudio.google.com/s/vmuQF5RNWoI',
    comune_denominazione: 'Vallelunga Pratameno',
    slug: 'vallelunga-pratameno',
  },
  {
    comune_codice_istat: 85022,
    mobile: 'https://datastudio.google.com/s/ojUS7KeVx3g',
    desktop: 'https://datastudio.google.com/s/i9PcfQ2jY4w',
    comune_denominazione: 'Villalba',
    slug: 'villalba',
  },
]
export default comuni
