name: aggiorna dati comuni provincia di Caltanissetta

on:
  push:
    paths:
    - 'dati/rawdata/provinciaCaltanissetta/source/**'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: installa csvkit e miller
      run: |-
        sudo pip install csvkit
        sudo apt-get install miller
    - name: aggiorna dati
      run: |-
        cd ./script/provinciaCaltanissetta
        chmod +x ./provinciaCaltanissetta.sh
        ./provinciaCaltanissetta.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "aggiornamentoDatiCl: ${timestamp}" || exit 0
        git push
